import { ArrowLeft, ChevronRight, Lock } from 'lucide-react';
import React from 'react';

const methods = [
	{
		id: 'auth_app',
		name: 'Auth App',
		description: '',
		inputTitle: '',
		placeholder: '',
	},
	{
		id: 'sms',
		name: 'SMS',
		description: `We'll send verification codes to this number.`,
		inputTitle: 'Phone number',
		// inputIcon: <Smartphone className='h-5 w-5'/>,
		inputPlaceholder: '+212 636299821'
	},
	{
		id: 'email',
		name: 'Email',
		description: `We'll send verification codes to this email address.`,
		inputTitle: 'Email',
		// inputIcon: <Mail className='h-5 w-5'/>,
		inputPlaceholder: 'iassil@student.1337.ma'
	}
];

export default function VerifySetup({ selectedMethod, onSubmit, goBack }) {
	const method = methods.find(m => m.id === selectedMethod);
	
	if (!method)
		return null;

	const contact = method?.id === 'sms' ? '+212636299821' : method?.id === 'email' ? 'iassil@student.1337.ma' : '';

	return (
		<>
			<div className='flex flex-col gap-2 mb-2'>
				<div className='flex flex-row gap-4 items-center'>
					<button className='cursor-pointer' onClick={goBack}>
						<ArrowLeft className='h-7 w-7' />
					</button>
					{/* <img src='/icons/lock.svg' className='h-full w-[8%]'/> */}
					<h1 className='font-semibold text-3xl'>{`Verify 2FA via ${method.name}`}</h1>
				</div>
				<p className='mb-0 text-white/75'>{`Enter the code ${contact ? `sent to ${contact}` : `generated by your authenticator app`}`}</p>
			</div>

			<form className='flex flex-col gap-4' >
				<div className='field flex flex-col gap-0.5 box-border'>
					<label htmlFor="code">Verification Code</label>
					<div className='flex flex-row pl-3.5 pr-3.5 pb-2 pt-2 gap-3 items-center h-11 bg-white/6 rounded-lg custom-input border border-white/10'>
						{/* <Image alt="Phone" src={'/icons/mail.svg'} width={20} height={20}></Image> */}
						<Lock className='h-5 w-5' />
						<input id='phone' name='phone' type='text' placeholder={method.inputPlaceholder} className='outline-none flex-1 overflow-hidden'/>
					</div>
				</div>
				{/* <AnimatePresence>
					{error && <FormFieldError error={error} />}
				</AnimatePresence> */}
				<button className='h-11 w-fit self-end pl-4 pr-2 bg-blue-600 hover:bg-blue-700 rounded-lg mt-2 flex justify-center items-center gap-2'
				onClick={() => onSubmit('123123') }>Continue<ChevronRight /></button>
			</form>
		</>
	);
}
