import { ArrowLeft, ChevronRight, Lock } from 'lucide-react';
import React from 'react';

interface VerifySetupProps {
	selectedMethod: string,
	contactMethod: string,
	onSubmit: ((contact: string) => void) | (() => void),
	onGoBack: () => void
}

export default function VerifySetup({ selectedMethod, contactMethod, onSubmit, onGoBack } : VerifySetupProps) {
	const methodName = selectedMethod === 'auth_app' ? 'Auth App' : selectedMethod === 'sms' ? 'SMS' : selectedMethod === 'email' ? 'Email' : '';
	const description = 'Enter the 6-digit code ' + (selectedMethod === 'auth_app' ? 'generated by your Authenticator App' : `sent to ${contactMethod}`);

	return (
		<>
			<div className='flex flex-col gap-2 mb-2'>
				<div className='flex flex-row gap-4 items-center'>
					<button className='cursor-pointer' onClick={onGoBack}>
						<ArrowLeft className='h-7 w-7' />
					</button>
					{/* <img src='/icons/lock.svg' className='h-full w-[8%]'/> */}
					<h1 className='font-semibold text-3xl'>Verify 2FA via {methodName}</h1>
				</div>
				<p className='mb-0 text-white/75'>{description}</p>
			</div>

			<form className='flex flex-col gap-4' >
				<div className='field flex flex-col gap-0.5 box-border'>
					<label htmlFor="code">Verification Code</label>
					<div className='flex flex-row pl-3.5 pr-3.5 pb-2 pt-2 gap-3 items-center h-11 bg-white/6 rounded-lg custom-input border border-white/10'>
						{/* <Image alt="Phone" src={'/icons/mail.svg'} width={20} height={20}></Image> */}
						<Lock className='h-5 w-5' />
						<input id='phone' name='phone' type='text' placeholder='6-digit code' className='outline-none flex-1 overflow-hidden'/>
					</div>
				</div>
				{/* <AnimatePresence>
					{error && <FormFieldError error={error} />}
				</AnimatePresence> */}
				<button className='h-11 w-fit self-end pl-4 pr-2 bg-blue-600 hover:bg-blue-700 rounded-lg mt-2 flex justify-center items-center gap-2'
				onClick={() => onSubmit('123123') }>Continue<ChevronRight /></button>
			</form>
		</>
	);
}
