{
 "title": "Kibana",
 "description": "Simple Kibana dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(kibana_millis_uptime)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kibana_status{instance='$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kibana_heap_used_in_bytes{instance='$instance'}",
     "legendFormat": "Heap used"
    },
    {
     "expr": "kibana_heap_max_in_bytes{instance='$instance'}",
     "legendFormat": "Heap Max "
    }
   ]
  },
  {
   "title": "FD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_max_fds{instance='$instance'}",
     "legendFormat": "Max fd"
    },
    {
     "expr": "process_open_fds{instance='$instance'}",
     "legendFormat": "Open fd"
    }
   ]
  },
  {
   "title": "LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "kibana_os_load_1m{instance=~'$instance'}",
     "legendFormat": "1m"
    },
    {
     "expr": "kibana_os_load_5m{instance=~'$instance'}",
     "legendFormat": "5m"
    },
    {
     "expr": "kibana_os_load_15m{instance=~'$instance'}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kibana_millis_uptime{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(kibana_requests_total{instance='$instance'}[1m])",
     "legendFormat": "req/m"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "kibana_requests_total{instance='$instance'}",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "kibana_concurrent_connections{instance='$instance'}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Response Avarage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kibana_response_average{instance='$instance'}",
     "legendFormat": "Response Average ms"
    }
   ]
  },
  {
   "title": "Request Disconnect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "kibana_requests_disconnects{instance='$instance'}",
     "legendFormat": "Request Disconnects"
    }
   ]
  }
 ]
}