{
 "title": "Logstash monitoring",
 "description": "System, JVM, Pipeline and individual plugin stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(logstash_up)" } },
   {
    "name": "pipeline",
    "query": {
     "query": "query_result(logstash_pipeline_events_in{instance=~'$instance'})"
    }
   },
   {
    "name": "plugin_id",
    "query": {
     "query": "query_result(logstash_pipeline_plugins_filters_events_duration_in_millis{instance=~'$instance'})"
    }
   },
   {
    "name": "input_plugin",
    "query": {
     "query": "query_result(logstash_pipeline_plugins_inputs_events_out{instance=~'$instance'})"
    }
   },
   {
    "name": "output_plugin",
    "query": {
     "query": "query_result(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance'})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logstash_up{instance=~'$instance'}",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstash_pipeline_events_in{instance='$instance',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(increase(logstash_pipeline_events_out{instance='$instance',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "OUT"
    },
    {
     "expr": "sum(increase(logstash_pipeline_events_in{instance='$instance',pipeline=~'$pipeline'}[$__range]))-sum(increase(logstash_pipeline_events_out{instance='$instance',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Bulk Stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logstash_pipeline_plugins_outputs_bulk_requests_successes{instance=~'$instance',pipeline=~'$pipeline'})",
     "legendFormat": "Bulk Success"
    },
    {
     "expr": "sum(logstash_pipeline_plugins_outputs_bulk_requests_with_errors{instance=~'$instance',pipeline=~'$pipeline'})",
     "legendFormat": "Bulk Errors"
    }
   ]
  },
  {
   "title": "Logstash ps total vmem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_process_mem_total_virtual_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-logstash_total_vmem"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logstash_jvm_uptime_in_millis{instance=~'$instance'}",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Logstash ps fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logstash_process_max_file_descriptors{instance=~'$instance'}",
     "legendFormat": " {{instance_pqdn}}-max_fds"
    },
    {
     "expr": "logstash_process_open_file_descriptors{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-open_fds"
    },
    {
     "expr": "logstash_process_peak_open_file_descriptors{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-peak_open_fds"
    }
   ]
  },
  {
   "title": "Pipeline Reloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "logstash_pipeline_reloads_last_success_timestamp{instance=~'$instance',pipeline=~'$pipeline'}*1000",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Old pool usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_mem_pools_old_committed_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-old_pool_committed"
      },
      {
       "expr": "logstash_jvm_mem_pools_old_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-old_pool_max"
      },
      {
       "expr": "logstash_jvm_mem_pools_old_peak_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-old_pool_peak_max"
      },
      {
       "expr": "logstash_jvm_mem_pools_old_peak_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-old_pool_peak_used"
      },
      {
       "expr": "logstash_jvm_mem_pools_old_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-old_used"
      }
     ]
    },
    {
     "title": "Young pool usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_mem_pools_young_committed_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-young_pool_commited"
      },
      {
       "expr": "logstash_jvm_mem_pools_young_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-young_pool_max"
      },
      {
       "expr": "logstash_jvm_mem_pools_young_peak_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-young_pool_peak_max"
      },
      {
       "expr": "logstash_jvm_mem_pools_young_peak_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-young_pool_peak_used"
      },
      {
       "expr": "logstash_jvm_mem_pools_young_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-young_pool_used"
      }
     ]
    },
    {
     "title": "Survivor pool usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_mem_pools_survivor_committed_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-survivor_pool_commited"
      },
      {
       "expr": "logstash_jvm_mem_pools_survivor_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-survivor_pool_max"
      },
      {
       "expr": "logstash_jvm_mem_pools_survivor_peak_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-survivor_pool_peak_max"
      },
      {
       "expr": "logstash_jvm_mem_pools_survivor_peak_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-survivor_pool_peak_used"
      },
      {
       "expr": "logstash_jvm_mem_pools_survivor_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-survivor_pool_used"
      }
     ]
    },
    {
     "title": "Old Colletions Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceil(increase(logstash_jvm_gc_collectors_old_collection_count{instance='$instance'}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time spent for GC (yound & old gens in ms)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_gc_collectors_old_collection_time_in_millis{instance=~'$instance'}/logstash_jvm_gc_collectors_old_collection_count{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-gc-old"
      },
      {
       "expr": "logstash_jvm_gc_collectors_young_collection_time_in_millis{instance=~'$instance'}/logstash_jvm_gc_collectors_young_collection_count{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-gc-young"
      }
     ]
    },
    {
     "title": "Threads count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_threads_count{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-threads_count"
      },
      {
       "expr": "logstash_jvm_threads_peak_count{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-threads_peak"
      }
     ]
    },
    {
     "title": "Young Colletions Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceil(increase(logstash_jvm_gc_collectors_young_collection_count{instance='$instance'}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Heap % used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_mem_heap_used_percent{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-jvm-usage"
      }
     ]
    },
    {
     "title": "JVM Heap usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "logstash_jvm_mem_heap_max_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-jvm-max"
      },
      {
       "expr": "logstash_jvm_mem_heap_used_in_bytes{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}}-jvm-used"
      }
     ]
    }
   ]
  },
  { "title": "Events Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Event Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_events_duration_in_millis{instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Event Duration"
    }
   ]
  },
  {
   "title": "Event In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_events_in{instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Events In"
    },
    {
     "expr": "irate(logstash_events_out{instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Events Out"
    }
   ]
  },
  {
   "title": "Event Queue Push Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_events_queue_push_duration_in_millis{instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "events_queue_push_duration"
    }
   ]
  },
  {
   "title": "Event Filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_events_filtered{instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Event Filtered"
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipelines Events I/O",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "ceil(increase(logstash_pipeline_events_in{instance='$instance',pipeline=~'$pipeline'}[$__range]))"
    },
    {
     "expr": "ceil(increase(logstash_pipeline_events_out{instance='$instance',pipeline=~'$pipeline'}[$__range]))"
    },
    {
     "expr": "increase(logstash_pipeline_events_duration_in_millis{instance='$instance',pipeline=~'$pipeline'}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(logstash_pipeline_events_filtered{instance='$instance',pipeline=~'$pipeline'}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(logstash_pipeline_events_queue_push_duration_in_millis{instance='$instance',pipeline=~'$pipeline'}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Event Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_events_duration_in_millis{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Event In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_events_in{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Queue Push Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_events_queue_push_duration_in_millis{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Event Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_events_out{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Event Filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_events_filtered{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  { "title": "Pipeline input plugins", "type": "text", "gridPos": { "h": 1, "w": 19, "x": 2, "y": 68 } },
  {
   "title": "Pipeline Input Plugins Queue Duration ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_inputs_events_queue_push_duration_in_millis{instance=~'$instance',pipeline=~'$pipeline',id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Input Plugin Events Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_inputs_events_out{instance=~'$instance',pipeline=~'$pipeline',id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  { "title": "Pipelines filters", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Pipelines Filter I/O",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "ceil(increase(logstash_pipeline_plugins_filters_events_in{instance='$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__range]))"
    },
    {
     "expr": "ceil(increase(logstash_pipeline_plugins_filters_events_out{instance='$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__range]))"
    },
    {
     "expr": "increase(logstash_pipeline_plugins_filters_events_duration_in_millis{instance='$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Filters Event Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_filters_events_duration_in_millis{instance=~'$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Filters Event In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_filters_events_in{instance=~'$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Filteres matches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_filters_matches{instance=~'$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__range])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Filters Event Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_filters_events_out{instance=~'$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__range])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Filteres failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_filters_failures{instance=~'$instance',pipeline=~'$pipeline',id=~'$plugin_id'}[$__range])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  { "title": "Pipelines Output", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Pipelines Output I/O",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "ceil(increase(logstash_pipeline_plugins_outputs_events_in{instance=~'$instance',pipeline=~'$pipeline',id=~'$output_plugin'}[$__range]))"
    },
    {
     "expr": "ceil(increase(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance',pipeline=~'$pipeline',id=~'$output_plugin'}[$__range]))"
    }
   ]
  },
  {
   "title": "Pipeline Output Event Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_outputs_events_duration_in_millis{instance=~'$instance',pipeline=~'$pipeline',id=~'$output_plugin'}[$__range])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Output Events In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_outputs_events_in{instance=~'$instance',pipeline=~'$pipeline',id=~'$output_plugin'}[$__range])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Bulk Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(irate(logstash_pipeline_plugins_outputs_bulk_requests_successes{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))/(sum(irate(logstash_pipeline_plugins_outputs_bulk_requests_successes{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))+sum(irate(logstash_pipeline_plugins_outputs_bulk_requests_with_errors{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]) OR vector(0))))*100",
     "legendFormat": "Bulk Success"
    },
    {
     "expr": "(sum(irate(logstash_pipeline_plugins_outputs_bulk_requests_with_errors{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))/(sum(irate(logstash_pipeline_plugins_outputs_bulk_requests_successes{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))+sum(irate(logstash_pipeline_plugins_outputs_bulk_requests_with_errors{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))))*100",
     "legendFormat": "Bulk Errors"
    }
   ]
  },
  {
   "title": "Pipeline Output Event Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance',pipeline=~'$pipeline',id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Bulk Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceil(irate(logstash_pipeline_plugins_outputs_bulk_requests_with_errors{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Pipeline Bulk Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceil(irate(logstash_pipeline_plugins_outputs_bulk_requests_successes{instance=~'$instance',pipeline=~'$pipeline'}[$__rate_interval]))",
     "legendFormat": "{{pipeline}} - {{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipeline Max Queue Size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logstash_pipeline_queue_max_queue_size_in_bytes{instance=~'$instance',pipeline=~'$pipeline'}",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "Pipeline Queue Events Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "logstash_pipeline_queue_events_count{instance=~'$instance',pipeline=~'$pipeline'}",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "Pipeline Max Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "logstash_pipeline_queue_queue_size_in_bytes{instance=~'$instance',pipeline=~'$pipeline'}",
       "legendFormat": "{{pipeline}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Strange Things",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipeline input events / sec over the last hour",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(logstash_pipeline_events_in{instance=~'$instance'}[$__range])",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "Pipeline output events / sec over the last hour",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance'}[$__range])",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "Events processing times",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "logstash_pipeline_events_queue_push_duration_in_millis{instance=~'$instance'}/logstash_pipeline_events_in{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}} - avg waiting time"
      },
      {
       "expr": "logstash_pipeline_events_duration_in_millis{instance=~'$instance'}/logstash_pipeline_events_out{instance=~'$instance'}",
       "legendFormat": "{{instance_pqdn}} - avg process time"
      }
     ]
    },
    {
     "title": "Processed events (I/O)/ sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "logstash_pipeline_events_in{instance=~'$instance'}/(logstash_pipeline_events_queue_push_duration_in_millis{instance=~'$instance'}/1000)",
       "legendFormat": "{{pipeline}} - pushed events/sec"
      }
     ]
    },
    {
     "title": "Output events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance',id=~'$output_plugin'}[$__range])",
       "legendFormat": "{{instance_pqdn}}"
      }
     ]
    }
   ]
  }
 ]
}