### Match 1
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 23,
    "score": 2
  },
  "player2": {
    "ID": 67,
    "score": 3
  },
  "gameStartedAt": 1740961200,
  "gameFinishedAt": 1740961265,
  "gameType": "XO"
}

### Match 2
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 45,
    "score": 3
  },
  "player2": {
    "ID": 89,
    "score": 8
  },
  "gameStartedAt": 1741047600,
  "gameFinishedAt": 1741047662,
  "gameType": "PONG"
}

### Match 3
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 12,
    "score": 1
  },
  "player2": {
    "ID": 78,
    "score": 3
  },
  "gameStartedAt": 1741134000,
  "gameFinishedAt": 1741134058,
  "gameType": "XO"
}

### Match 4
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 56,
    "score": 3
  },
  "player2": {
    "ID": 34,
    "score": 10
  },
  "gameStartedAt": 1741220400,
  "gameFinishedAt": 1741220467,
  "gameType": "PONG"
}

### Match 5
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 91,
    "score": 3
  },
  "player2": {
    "ID": 22,
    "score": 0
  },
  "gameStartedAt": 1741306800,
  "gameFinishedAt": 1741306863,
  "gameType": "XO"
}

### Match 6
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 44,
    "score": 3
  },
  "player2": {
    "ID": 77,
    "score": 9
  },
  "gameStartedAt": 1741393200,
  "gameFinishedAt": 1741393259,
  "gameType": "PONG"
}

### Match 7
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 3,
    "score": 2
  },
  "player2": {
    "ID": 82,
    "score": 2
  },
  "gameStartedAt": 1741479600,
  "gameFinishedAt": 1741479661,
  "gameType": "XO"
}

### Match 8
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 63,
    "score": 6
  },
  "player2": {
    "ID": 29,
    "score": 6
  },
  "gameStartedAt": 1741566000,
  "gameFinishedAt": 1741566064,
  "gameType": "PONG"
}

### Match 9
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 38,
    "score": 1
  },
  "player2": {
    "ID": 95,
    "score": 1
  },
  "gameStartedAt": 1740964800,
  "gameFinishedAt": 1740964862,
  "gameType": "XO"
}

### Match 10
POST https://localhost/api/users/matches
Authorization: Bearer not-secure-api-key-just-for-dev
Content-Type: application/json

{
  "player1": {
    "ID": 71,
    "score": 10
  },
  "player2": {
    "ID": 53,
    "score": 7
  },
  "gameStartedAt": 1741051200,
  "gameFinishedAt": 1741051263,
  "gameType": "PONG"
}