volumes:
    grafana-data:
        driver: local
    prometheus-data:
        driver: local
    alertmanager-data:
        driver: local
    grafana-ssl:
        driver: local

networks:
    monitoring:
        driver: bridge

services:
    grafana:
        image: grafana/grafana:12.0.1
        container_name: grafana
        restart: always
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - PROMETHEUS_HOST_URL=${PROMETHEUS_HOST_URL}
        networks:
            - monitoring
            - web-app
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:3000"]
            interval: 30s
            timeout: 10s
            retries: 10

    prometheus:
        image: prom/prometheus:v3.4.0
        container_name: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
            - prometheus-data:/prometheus
        networks:
            - monitoring
        command:
            - "--storage.tsdb.retention.time=20d" # Data retention (20 days)
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"

    alertmanager:
        image: prom/alertmanager:v0.28.0
        container_name: alertmanager
        restart: always
        volumes:
            - ./prometheus/alertmanager.yml:/config/alertmanager.yml
            - ./prometheus/mail.key:/etc/alertmanager/secrets/mail.key
            - alertmanager-data:/data
        command:
            - "--config.file=/config/alertmanager.yml --log.level=debug"

include:
    - ./compose.exporters.yaml
