"use client";

import Image from "next/image";
import Form from "next/form";
import Link from "next/link";
import ibm from "../fonts/ibm";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";

const numberInputStyling =
	"w-full h-20 .no-spinner text-xl text-center mt-[7px] outline-none bg-bg border-bbg flex items-center justify-center \
						gap-[7px] border-2 rounded-lg hover:ring-4 hover:ring-bbg hover:bg-hbbg focus:ring-bbg focus:ring-4";

export default function Auth() {
	const router = useRouter();
	const [inputs, setInputs] = useState(Array(6).fill(""));
	const buttonRef = useRef<HTMLButtonElement>(null);

	function handleChange(index: number, value: string) {
		const updatedInputs = [...inputs];
		updatedInputs[index] = value;
		setInputs(updatedInputs);

		if (value && index < 5) {
			const nextInput = document.getElementById(`input-${index + 1}`);
			if (nextInput) {
				nextInput.focus();
			}
		} else {
			buttonRef.current?.focus();
		}
	}
	const api = "l";

	return (
		<div className="h-screen flex flex-col">
			<nav className="h-30 flex align-center pl-16">
				<Image
					src="/rallyu-logo.svg"
					alt="Logo"
					width={0}
					height={0}
					style={{ width: "auto", height: "auto" }}
					onClick={(e) => {
						e.preventDefault();
						router.push("/");
					}}
					className="hover:cursor-pointer hover:scale-101 transition-transform duration-200"
				></Image>
			</nav>
			<main className="flex-1 flex justify-center items-center">
				<div className="w-[450px]">
					<h1
						className={`${ibm.className} text-[36px] font-bold flex justify-center`}
					>
						Authentication
					</h1>
					<p className={`flex justify-center text-[18px] mb-[47px]`}>
						Enter the code generated by your Authentication App
					</p>
					<Form action={api}>
						<div className="flex gap-[7px]">
							{inputs.map((inputValue, index) => (
								<input
									key={index}
									id={`input-${index}`}
									type="number"
									value={inputValue}
									className={numberInputStyling}
									onChange={(e) => handleChange(index, e.target.value)}
									maxLength={1}
									placeholder="*"
									required
								/>
							))}
						</div>
						<div className="mt-[19px] flex justify-center">
							<p>
								Didn&apos;t get the code?{" "}
								<Link
									href="/signup"
									className="text-main hover:text-blue-400 hover:underline"
								>
									Resend code
								</Link>
							</p>
						</div>
						<button
							ref={buttonRef}
							type="submit"
							className="w-full h-13 rounded-lg bg-main mt-[44px] flex justify-center
								items-center hover:cursor-pointer hover:ring-3 hover:ring-main-ring-hover hover:bg-main-hover
								active:bg-main-active active:ring-main-ring-active"
						>
							Verify account
						</button>
					</Form>
					<div className="mt-[19px] flex justify-center">
						<p>
							Can’t access your Authentication app?{" "}
							<Link
								href="/signup"
								className="text-main hover:text-blue-400 hover:underline"
							>
								Contact Support
							</Link>
						</p>
					</div>
				</div>
			</main>
		</div>
	);
}
