networks:
  frontend:
    driver: bridge

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     image: rallyu/frontend:v1.0
#     container_name: frontend
#     restart: always
#     networks:
#       - frontend
#       - web-app
#     healthcheck:
#       test:
#         [
#           "CMD-SHELL",
#           "curl -sfI http://localhost:3000 | grep -qE '^HTTP/(1\\.1|2) 200'",
#         ]
#       interval: 30s
#       timeout: 10s
#       retries: 20

include:
  - ./backend/compose.backend.yaml
