networks:
    frontend:
        driver: bridge

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: frontend:rallyu
        container_name: frontend
        restart: always
        networks:
            - frontend
            - web-app
        healthcheck:
            test:
                [
                   "CMD",
                    "curl -I http://localhost:3000 | grep -qE 'HTTP/(1\\.1|2) 200'",
                ]
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 10s

include:
    - ./backend/compose.backend.yaml
