networks:
    backend:
        driver: bridge

volumes:
    ms-auth-data:
        driver: local

services:
    api-gateway:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        depends_on:
            nats:
                condition: service_healthy
        image: rallyu/api-gateway:v1.0
        container_name: api-gateway
        restart: always
        ports:
          - 4025:4025
        networks:
            - backend
            # - web-app
        env_file:
            # - ./api-gateway/.env
            - .env
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'curl -sf http://localhost:4025/health | grep -q "\"status\":\"up\""',
                ]
            interval: 10s
            timeout: 10s
            retries: 20

    nats:
        image: nats:alpine3.22
        container_name: nats
        restart: always
        networks:
            - backend
        env_file:
            - .env
        ports:
          - 4222:4222
        command: --user ${NATS_USER} --pass ${NATS_PASSWORD} -js -m 8222 -n internal-server
        healthcheck:
            test: wget http://localhost:8222/healthz -q -S -O -
            start_period: 2s
            interval: 10s
            timeout: 10s
            retries: 3

    nats_ui:
        image: mdawar/nats-dashboard
        container_name: nats_ui
        ports: # TODO: To be removed
            - 8571:80
        restart: always
        networks:
            - backend
            # - web-app
        volumes:
            - ./nats_ui_config/config.json:/srv/config.json
