networks:
  backend:
    driver: bridge

volumes:
  ms-auth-data:
    driver: local

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      nats:
        condition: service_healthy
    image: rallyu/api-gateway:v1.0
    container_name: api-gateway
    restart: always
    networks:
      - backend
      - web-app
    env_file:
      - ./api-gateway/.api-gateway.env
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -sf http://localhost:4025/health | grep -q "\"status\":\"up\""',
        ]
      start_period: 2s
      interval: 5s
      timeout: 10s
      retries: 10
    develop:
      watch:
        - path: ./api-gateway
          action: sync
          target: /app
          ignore:
            - node_modules/
        - path: ./api-gateway/package.json
          action: rebuild

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-auth:v1.0
    container_name: ms-auth
    restart: always
    volumes:
      - ./ms-auth/src/database/database.db:/app/src/database/database.db
      - ./ms-auth/uploads:/app/uploads
    networks:
      - backend
    env_file:
      - ./ms-auth/.auth.env
      - .env
    develop:
      watch:
        - path: ./ms-auth
          action: sync
          target: /app
          ignore:
            - ./ms-auth/node_modules/
            - ./ms-auth/src/database/database.db
        - path: ./ms-auth/package.json
          action: rebuild

  ms-notif:
    build:
      context: ./ms-notif
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-notif:v1.0
    container_name: ms-notif
    restart: always
    volumes:
      - ./ms-notif/database/database.sqlite:/app/database/database.sqlite
    networks:
      - backend
    env_file:
      - ./ms-notif/.notif.env
      - .env
    develop:
      watch:
        - path: ./ms-notif
          action: sync
          target: /app
          ignore:
            - ./ms-notif/node_modules/
            - ./ms-notif/database/
        - path: ./ms-notif/package.json
          action: rebuild

  ms-chat:
    build:
      context: ./ms-chat
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-chat:v1.0
    container_name: ms-chat
    volumes:
      - ./ms-chat/database/database.sqlite:/app/database/database.sqlite
    restart: always
    networks:
      - backend
    env_file:
      - ./ms-chat/.chat.env
      - .env
    develop:
      watch:
        - path: ./ms-chat/src/
          action: sync
          target: /app/src
          ignore:
            - ./ms-chat/node_modules/
            - ./ms-chat/database/

  ms-tournament:
    build:
      context: ms-tournament/
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-tournament:v1.0
    container_name: ms-tournament
    restart: always
    networks:
      - backend
    volumes:
      - ./ms-tournament/database/tournament.db:/app/database/tournament.db
    env_file:
      - .env
    develop:
      watch:
        - path: ./ms-tournament/
          action: sync
          target: /app/
          ignore:
            - ./ms-tournament/node_modules/
            - ./ms-tournament/database
        - path: ./ms-tournament/src/package.json
          action: rebuild

  ms-matchmaking:
    build:
      context: ms-matchmaking/
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-matchmaking
    container_name: ms-matchmaking
    restart: always
    networks:
      - backend
    env_file:
      - .env
      - ./ms-matchmaking/.matchmaking.env
    develop:
      watch:
        - path: ./ms-matchmaking
          action: sync
          target: /app
          ignore:
            - ./ms-matchmaking/node_modules/
        - path: ./ms-matchmaking/package.json
          action: rebuild

  ms-game:
    build:
      context: ms-game/
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-game
    container_name: ms-game
    restart: always
    networks:
      - backend
    env_file:
      - .env
      - ./ms-game/.game.env
    develop:
      watch:
        - path: ./ms-game
          action: sync
          target: /app
          ignore:
            - ./ms-game/node_modules/
        - path: ./ms-game/package.json
          action: rebuild

  redis:
    image: redis:alpine3.22
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - 6379:6379
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  nats:
    image: nats:alpine3.22
    container_name: nats
    restart: always
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 4222:4222
    command: --user ${NATS_USER} --pass ${NATS_PASSWORD} -js -m 8222 -n internal-server
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_period: 2s
      interval: 5s
      timeout: 10s
      retries: 10
