networks:
    backend:
        driver: bridge

volumes:
    ms-auth-data:
        driver: local

services:
    api-gateway:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        image: rallyu/api-gateway:v1.0
        container_name: api-gateway
        restart: always
        networks:
            - backend
            - web-app
        env_file:
            - ./api-gateway/.env
        healthcheck:
            test: ["CMD-SHELL", "curl -sf http://localhost:4004/health | grep -q '\"status\":\"up\"'"]
            interval: 30s
            timeout: 10s
            retries: 20

    ms-auth:
        build:
            context: ./ms-auth
            dockerfile: Dockerfile
        image: rallyu/ms-auth:v1.0
        container_name: ms-auth
        restart: always
        networks:
            - backend
        env_file:
            - ./ms-auth/.env
        volumes:
            - ms-auth-data:/app/database
