networks:
  backend:
    driver: bridge

volumes:
  ms-auth-data:
    driver: local

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      nats:
        condition: service_healthy
    image: rallyu/api-gateway:v1.0
    container_name: api-gateway
    restart: always
    ports:
      - 4025:4025
    networks:
      - backend
      - web-app
    env_file:
      - ./api-gateway/.env
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -sf http://localhost:4025/health | grep -q "\"status\":\"up\""',
        ]
      start_period: 2s
      interval: 5s
      timeout: 10s
      retries: 10
    develop:
      watch:
        - path: ./api-gateway
          action: sync+restart
          target: /app
          ignore:
            - node_modules/
        - path: ./api-gateway/package.json
          action: rebuild

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-auth:v1.0
    container_name: ms-auth
    restart: always
    volumes:
      - ./ms-auth/src/database/database.db:/app/src/database/database.db
      - ./ms-auth/uploads/avatars/:/app/uploads/avatars/
    networks:
      - backend
    env_file:
      - .env

  ms-notif:
    build:
      context: ./ms-notif
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-notif:v1.0
    container_name: ms-notif
    restart: always
    networks:
      - backend
    env_file:
      - .env
    develop:
      watch:
        - path: ./ms-notif
          action: sync+restart
          target: /app
          ignore:
            - node_modules/
        - path: ./ms-notif/package.json
          action: rebuild

  ms-chat:
    build:
      context: ./ms-chat
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-chat:v1.0
    container_name: ms-chat
    volumes:
      - ./ms-chat/database/:/app/database/
    restart: always
    networks:
      - backend
    env_file:
      - .env
    develop:
      watch:
        - path: ./ms-chat
          action: sync+restart
          target: /app
          ignore:
            - node_modules/

  ms-tournament:
    build:
      context: ms-tournament/
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-tournament:v1.0
    container_name: ms-tournament
    restart: always
    networks:
      - backend

  ms-matchmaking:
    build:
      context: ms-matchmaking/
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-matchmaking
    container_name: ms-matchmaking
    restart: always
    networks:
      - backend

  ms-game:
    build:
      context: ms-game/
      dockerfile: Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
    image: rallyu/ms-game
    container_name: ms-game
    restart: always
    networks:
      - backend

  redis:
    image: redis:alpine3.22
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - 6379:6379
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  redis_ui:
    image: redis/redisinsight:2.70
    container_name: redis_insight
    ports:
      - 5540:5540
    networks:
      - backend
    env_file:
      - .env
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_ALIAS=RallyuConnection
      - RI_REDIS_PASSWORD=${REDIS_PASSWORD}

  nats:
    image: nats:alpine3.22
    container_name: nats
    restart: always
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 4222:4222
    command: --user ${NATS_USER} --pass ${NATS_PASSWORD} -js -m 8222 -n internal-server
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_period: 2s
      interval: 5s
      timeout: 10s
      retries: 10

  nats_ui:
    image: mdawar/nats-dashboard
    container_name: nats_ui
    ports: # TODO: To be removed
      - 8571:80
    restart: always
    networks:
      - backend
      - web-app
    volumes:
      - ./nats_ui_config/config.json:/srv/config.json
