'use client';
import { useState } from "react";
import MethodSelection from "./components/MethodSelection";
import VerifyCode from "./components/VerifyCode";

export default function Login2FAChallengePage() {
	const [step, setStep] = useState<'enabled-methods' | 'submit-code'>('enabled-methods');
	const [selectedMethod, setSelectedMethod] = useState('');

	console.log('RENDERING LOGIN2FACHALLENGE');

	function handleMethodSelect(method: string) {
		setSelectedMethod(method);
		setStep('submit-code');
	}

	return (
		<>
			<main className="pt-30 flex h-[100vh] w-full pb-10">
				<div className="flex h-full w-full justify-center overflow-auto">
					<div className="mine flex h-full w-[650px] items-start justify-center pb-20 pl-10 pr-10 pt-20 lg:items-center">
						<div className='rounded-[0px] max-w-[550px] w-full p-9 sm:p-18
									flex flex-col gap-5'>
							{step === 'enabled-methods' && <MethodSelection onSelect={handleMethodSelect}/>}
							{step === 'submit-code' && <VerifyCode selectedMethod={selectedMethod} description={selectedMethod === 'totp' ? 'Enter the code generated by your Authentication App' : selectedMethod === 'email' ? 'Enter the code sent to you via Email' : 'Enter the code sent to you via SMS'} />}
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
